/*
 * This file is part of RasterLab
 * Copyright (c) 2026 Warren Galyen
 * All rights reserved.
 *
 * This software is provided as freeware for personal and commercial use.
 * Redistribution, modification, or reverse engineering is not permitted.
 * See LICENSE.txt for full terms.
 */

#include "commands/command_selection.h"
#include "command.h"
#include "document.h"
#include "selection.h"
#include "selection/selection_mask.h"
#include <glib.h>
#include <stdlib.h>

/**
 * Selection command apply callback (restore "after" state)
 */
static void selection_command_apply(Command* cmd, struct ImageDocument* doc) {
    SelectionCommandData* data;
    extern gboolean selection_undo_apply_after(SelectionMask*, SelectionUndoDelta*);

    if (!cmd || !cmd->user_data || !doc) {
        return;
    }

    data = (SelectionCommandData*)cmd->user_data;

    if (!data->mask || !data->delta) {
        return;
    }

    /* Apply "after" state for redo (includes feathering parameter restoration) */
    selection_undo_apply_after(data->mask, data->delta);

    /* Destroy cached surface to force rebuild from fresh mask data
       (feathered_preview was already regenerated by selection_undo_apply_after) */
    if (data->mask->surface) {
        cairo_surface_destroy(data->mask->surface);
        data->mask->surface = NULL;
    }
    data->mask->dirty = TRUE;

    /* Mark document dirty and trigger selection redraw */
    if (doc->drawing_area) {
        gtk_widget_queue_draw(doc->drawing_area);
    }
}

/**
 * Selection command revert callback (restore "before" state)
 */
static void selection_command_revert(Command* cmd, struct ImageDocument* doc) {
    SelectionCommandData* data;
    extern gboolean selection_undo_apply_before(SelectionMask*, SelectionUndoDelta*);

    if (!cmd || !cmd->user_data || !doc) {
        return;
    }

    data = (SelectionCommandData*)cmd->user_data;

    if (!data->mask || !data->delta) {
        return;
    }

    /* Apply "before" state for undo (includes feathering parameter restoration) */
    selection_undo_apply_before(data->mask, data->delta);

    /* Destroy cached surface to force complete rebuild
       (feathered_preview was already regenerated by selection_undo_apply_before) */
    if (data->mask->surface) {
        cairo_surface_destroy(data->mask->surface);
        data->mask->surface = NULL;
    }
    data->mask->dirty = TRUE;

    /* Mark document dirty and trigger selection redraw */
    if (doc->drawing_area) {
        gtk_widget_queue_draw(doc->drawing_area);
    }
}

/**
 * Selection command destroy callback
 */
static void selection_command_destroy(Command* cmd) {
    SelectionCommandData* data;
    extern void selection_undo_delta_free(SelectionUndoDelta*);

    if (!cmd || !cmd->user_data) {
        return;
    }

    data = (SelectionCommandData*)cmd->user_data;

    if (data->delta) {
        selection_undo_delta_free(data->delta);
    }

    g_free(data);
}

/**
 * Create a selection command
 * Wraps a SelectionUndoDelta for undo/redo
 */
Command* command_create_selection(struct SelectionMask* mask,
                                  SelectionUndoDelta* delta,
                                  struct ImageDocument* doc,
                                  const gchar* name) {
    Command* cmd;
    SelectionCommandData* data;
    const gchar* cmd_name;

    if (!mask || !delta || !doc) {
        return NULL;
    }

    cmd_name = name ? name : "Selection Operation";

    /* Create command data */
    data = (SelectionCommandData*)g_malloc(sizeof(SelectionCommandData));
    data->mask = mask;
    data->delta = delta; /* ownership transferred */
    data->doc = doc;

    /* Create command */
    cmd = command_new(cmd_name,
                      COMMAND_SELECTION,
                      selection_command_apply,
                      selection_command_revert,
                      selection_command_destroy);

    if (!cmd) {
        g_free(data);
        return NULL;
    }

    cmd->user_data = data;
    cmd->document = doc;

    return cmd;
}
