#ifndef VERSION_H
#define VERSION_H

#define RASTERLAB_VERSION_MAJOR 1
#define RASTERLAB_VERSION_MINOR 0
#define RASTERLAB_VERSION_PATCH 0

/* Adjacent string literals: "1" "." "0" "." "0" -> "1.0.0" */
#define RASTERLAB_STRINGIFY_HELPER(x) #x
#define RASTERLAB_STRINGIFY(x) RASTERLAB_STRINGIFY_HELPER(x)
#define RASTERLAB_VERSION_LINE \
    RASTERLAB_STRINGIFY(RASTERLAB_VERSION_MAJOR) "." \
    RASTERLAB_STRINGIFY(RASTERLAB_VERSION_MINOR) "." \
    RASTERLAB_STRINGIFY(RASTERLAB_VERSION_PATCH)

#endif /* VERSION_H */
